import { Router, type Request, type Response, type NextFunction } from 'express'
import { clerkClient, getAuth } from '@clerk/express'
import { z } from 'zod'
import { database } from './db'
import { issueRoomToken } from './livekit'

export const api = Router()
const id = z.string().trim().min(1).max(128)
const uuid = z.string().uuid()
const fail = (res: Response, status: number, code: string, message: string, details: unknown = {}) => res.status(status).json({ error: { code, message, details } })
const wrap = (fn: (req: Request, res: Response) => Promise<unknown>) => (req: Request, res: Response, next: NextFunction) => { void fn(req, res).catch(next) }
api.use((req, res, next) => {
  if (!process.env.CLERK_SECRET_KEY || !process.env.CLERK_PUBLISHABLE_KEY) return fail(res, 503, 'AUTH_UNAVAILABLE', 'Authentication is not configured.')
  if (!getAuth(req).userId) return fail(res, 401, 'UNAUTHENTICATED', 'Sign in to continue.')
  next()
})
const who = (req: Request) => getAuth(req).userId!
const profile = async (userId: string) => (await database().query('SELECT id,name,username,avatar_url AS "avatarUrl",created_at AS "createdAt" FROM users WHERE id=$1', [userId])).rows[0] ?? null
const syncProfile = async (userId: string) => {
  const u = await clerkClient.users.getUser(userId), name = [u.firstName,u.lastName].filter(Boolean).join(' ') || u.username || 'Studyspace user'
  await database().query(`INSERT INTO users(id,name,username,avatar_url) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,username=CASE WHEN EXISTS(SELECT 1 FROM users WHERE username=EXCLUDED.username AND id<>EXCLUDED.id) THEN users.username ELSE EXCLUDED.username END,avatar_url=EXCLUDED.avatar_url,updated_at=now()`,[userId,name,u.username||null,u.imageUrl||null])
  return profile(userId)
}
const roomAccess = (room: string, user: string) => database().query('SELECT r.id,r.name,r.type,r.created_by AS "createdBy",m.role FROM study_rooms r JOIN room_members m ON m.room_id=r.id AND m.user_id=$2 WHERE r.id=$1 AND r.deleted_at IS NULL',[room,user])
const input = <T>(res: Response, schema: z.ZodType<T>, body: unknown): T | null => { const parsed=schema.safeParse(body); if(!parsed.success){fail(res,422,'VALIDATION_ERROR','Request validation failed.',parsed.error.flatten());return null}return parsed.data }
const param = (req: Request, name: string) => String(req.params[name] ?? '')

api.get('/me',wrap(async(req,res)=>res.json({user:await syncProfile(who(req))})))
api.get('/users/:userId',wrap(async(req,res)=>{const parsed=id.safeParse(param(req,'userId'));if(!parsed.success)return fail(res,422,'VALIDATION_ERROR','Invalid user ID.');let user=await profile(parsed.data);if(!user){try{user=await syncProfile(parsed.data)}catch{user=null}}return user?res.json({user:{id:user.id,name:user.name,username:user.username,avatarUrl:user.avatarUrl}}):fail(res,404,'USER_NOT_FOUND','The requested user does not exist.')}))
api.get('/friends',wrap(async(req,res)=>{const r=await database().query(`SELECT u.id,u.name,u.username,u.avatar_url AS "avatarUrl",'offline' AS status FROM friends f JOIN users u ON u.id=f.friend_id WHERE f.user_id=$1 ORDER BY u.name`,[who(req)]);return res.json({friends:r.rows})}))
api.get('/friends/requests',wrap(async(req,res)=>{const r=await database().query(`SELECT id,sender_id AS "senderId",receiver_id AS "receiverId",lower(status::text) AS status,created_at AS "createdAt" FROM friend_requests WHERE status='PENDING' AND (sender_id=$1 OR receiver_id=$1) ORDER BY created_at DESC`,[who(req)]);return res.json({incoming:r.rows.filter(x=>x.receiverId===who(req)),outgoing:r.rows.filter(x=>x.senderId===who(req))})}))
api.post('/friends/requests',wrap(async(req,res)=>{const b=input(res,z.object({userId:id}),req.body);if(!b)return;const sender=who(req),receiver=b.userId;if(sender===receiver)return fail(res,400,'SELF_FRIEND_REQUEST','You cannot send a friend request to yourself.');await syncProfile(sender);if(!await profile(receiver))return fail(res,404,'USER_NOT_FOUND','The requested user does not exist.');const db=database();if((await db.query('SELECT 1 FROM friends WHERE user_id=$1 AND friend_id=$2',[sender,receiver])).rowCount)return fail(res,409,'ALREADY_FRIENDS','This user is already your friend.');if((await db.query(`SELECT 1 FROM friend_requests WHERE status='PENDING' AND ((sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1))`,[sender,receiver])).rowCount)return fail(res,409,'REQUEST_EXISTS','A pending request already exists.');const r=await db.query(`INSERT INTO friend_requests(sender_id,receiver_id) VALUES($1,$2) RETURNING id,sender_id AS "senderId",receiver_id AS "receiverId",lower(status::text) AS status,created_at AS "createdAt"`,[sender,receiver]);return res.status(201).json({request:r.rows[0]})}))


api.post('/friends/requests/:requestId/accept',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'requestId'));if(!rid.success)return fail(res,422,'VALIDATION_ERROR','Invalid request ID.');const db=database(),cx=await db.connect(),user=who(req);try{await cx.query('BEGIN');const q=await cx.query(`SELECT sender_id,receiver_id FROM friend_requests WHERE id=$1 AND status='PENDING' FOR UPDATE`,[rid.data]);if(!q.rowCount){await cx.query('ROLLBACK');return fail(res,404,'REQUEST_NOT_FOUND','Pending friend request not found.')}if(q.rows[0].receiver_id!==user){await cx.query('ROLLBACK');return fail(res,403,'FORBIDDEN','Only the recipient can accept this request.')}const friend=q.rows[0].sender_id;await cx.query('INSERT INTO friends(user_id,friend_id) VALUES($1,$2),($2,$1) ON CONFLICT DO NOTHING',[user,friend]);await cx.query(`UPDATE friend_requests SET status='ACCEPTED',updated_at=now() WHERE id=$1`,[rid.data]);await cx.query('COMMIT');return res.json({success:true,friendId:friend})}catch(e){await cx.query('ROLLBACK');throw e}finally{cx.release()}}))
api.delete('/friends/requests/:requestId',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'requestId'));if(!rid.success)return fail(res,422,'VALIDATION_ERROR','Invalid request ID.');const r=await database().query(`UPDATE friend_requests SET status=CASE WHEN sender_id=$2 THEN 'CANCELLED'::friend_request_status ELSE 'REJECTED'::friend_request_status END,updated_at=now() WHERE id=$1 AND status='PENDING' AND (sender_id=$2 OR receiver_id=$2)`,[rid.data,who(req)]);return r.rowCount?res.status(204).end():fail(res,404,'REQUEST_NOT_FOUND','Pending friend request not found.')}))

api.post('/rooms',wrap(async(req,res)=>{const b=input(res,z.object({name:z.string().trim().min(1).max(100),type:z.enum(['PRIVATE_CALL','GROUP_CALL','STUDY_ROOM'])}),req.body);if(!b)return;const user=who(req);await syncProfile(user);const db=database(),cx=await db.connect();try{await cx.query('BEGIN');if(b.type==='PRIVATE_CALL'&&(await cx.query("SELECT 1 FROM study_rooms WHERE type='PRIVATE_CALL' AND created_by=$1 AND deleted_at IS NULL",[user])).rowCount)return (await cx.query('ROLLBACK'),fail(res,409,'PRIVATE_ROOM_EXISTS','Use an existing private room for this user.'));const r=await cx.query('INSERT INTO study_rooms(name,type,created_by) VALUES($1,$2,$3) RETURNING id,name,type,created_by AS "createdBy",created_at AS "createdAt"',[b.name,b.type,user]);await cx.query("INSERT INTO room_members(room_id,user_id,role) VALUES($1,$2,'OWNER')",[r.rows[0].id,user]);await cx.query('COMMIT');return res.status(201).json({room:r.rows[0]})}catch(e){await cx.query('ROLLBACK');throw e}finally{cx.release()}}))
api.get('/rooms',wrap(async(req,res)=>{const r=await database().query(`SELECT r.id,r.name,r.type,m.role,(SELECT count(*)::int FROM room_members x WHERE x.room_id=r.id) AS "participantCount" FROM study_rooms r JOIN room_members m ON m.room_id=r.id WHERE m.user_id=$1 AND r.deleted_at IS NULL ORDER BY r.created_at DESC`,[who(req)]);return res.json({rooms:r.rows})}))
api.get('/rooms/:roomId',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'roomId'));if(!rid.success)return fail(res,422,'VALIDATION_ERROR','Invalid room ID.');const access=await roomAccess(rid.data,who(req));if(!access.rowCount)return fail(res,404,'ROOM_NOT_FOUND','The requested room does not exist or you do not have access.');const members=await database().query(`SELECT m.user_id AS "userId",u.name,m.role FROM room_members m JOIN users u ON u.id=m.user_id WHERE m.room_id=$1 ORDER BY m.joined_at`,[rid.data]);return res.json({room:{...access.rows[0],participants:members.rows}})}))
api.delete('/rooms/:roomId',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'roomId'));if(!rid.success)return fail(res,422,'VALIDATION_ERROR','Invalid room ID.');const access=await roomAccess(rid.data,who(req));if(!access.rowCount)return fail(res,404,'ROOM_NOT_FOUND','Room not found.');if(access.rows[0].role!=='OWNER')return fail(res,403,'FORBIDDEN','Only the room owner can delete this room.');await database().query('UPDATE study_rooms SET deleted_at=now() WHERE id=$1',[rid.data]);return res.status(204).end()}))
api.post('/rooms/:roomId/members',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'roomId'));if(!rid.success)return fail(res,422,'VALIDATION_ERROR','Invalid room ID.');const b=input(res,z.object({userId:id,role:z.enum(['OWNER','MODERATOR','MEMBER']).default('MEMBER')}),req.body);if(!b)return;const access=await roomAccess(rid.data,who(req));if(!access.rowCount)return fail(res,404,'ROOM_NOT_FOUND','Room not found.');if(!['OWNER','MODERATOR'].includes(access.rows[0].role))return fail(res,403,'FORBIDDEN','You cannot add room members.');if(b.role==='OWNER'&&access.rows[0].role!=='OWNER')return fail(res,403,'FORBIDDEN','Only the owner can grant the owner role.');if(!await profile(b.userId))return fail(res,404,'USER_NOT_FOUND','The requested user does not exist.');const r=await database().query('INSERT INTO room_members(room_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(room_id,user_id) DO NOTHING RETURNING room_id',[rid.data,b.userId,b.role]);if(!r.rowCount)return fail(res,409,'ALREADY_MEMBER','User is already a room member.');return res.status(201).json({success:true})}))
api.get('/rooms/:roomId/members',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'roomId'));if(!rid.success)return fail(res,422,'VALIDATION_ERROR','Invalid room ID.');if(!(await roomAccess(rid.data,who(req))).rowCount)return fail(res,404,'ROOM_NOT_FOUND','Room not found.');const r=await database().query(`SELECT m.user_id AS "userId",u.name,m.role,m.joined_at AS "joinedAt" FROM room_members m JOIN users u ON u.id=m.user_id WHERE m.room_id=$1 ORDER BY m.joined_at`,[rid.data]);return res.json({members:r.rows})}))
api.delete('/rooms/:roomId/members/:userId',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'roomId')),target=id.safeParse(param(req,'userId'));if(!rid.success||!target.success)return fail(res,422,'VALIDATION_ERROR','Invalid room or user ID.');const access=await roomAccess(rid.data,who(req));if(!access.rowCount)return fail(res,404,'ROOM_NOT_FOUND','Room not found.');const same=who(req)===target.data;if(!same&&access.rows[0].role==='MEMBER')return fail(res,403,'FORBIDDEN','You cannot remove this member.');const targetRole=await database().query('SELECT role FROM room_members WHERE room_id=$1 AND user_id=$2',[rid.data,target.data]);if(targetRole.rows[0]?.role==='OWNER')return fail(res,403,'FORBIDDEN','The room owner cannot be removed.');const r=await database().query('DELETE FROM room_members WHERE room_id=$1 AND user_id=$2',[rid.data,target.data]);return r.rowCount?res.status(204).end():fail(res,404,'MEMBER_NOT_FOUND','Room member not found.')}))

api.delete('/friends/:userId',wrap(async(req,res)=>{const friend=id.safeParse(param(req,'userId'));if(!friend.success)return fail(res,422,'VALIDATION_ERROR','Invalid user ID.');const db=database(),cx=await db.connect();try{await cx.query('BEGIN');await cx.query('DELETE FROM friends WHERE (user_id=$1 AND friend_id=$2) OR (user_id=$2 AND friend_id=$1)',[who(req),friend.data]);await cx.query('COMMIT');return res.status(204).end()}catch(e){await cx.query('ROLLBACK');throw e}finally{cx.release()}}))

api.post('/rooms/:roomId/token',wrap(async(req,res)=>{const rid=uuid.safeParse(param(req,'roomId'));if(!rid.success)return fail(res,422,'VALIDATION_ERROR','Invalid room ID.');const b=input(res,z.object({publishAudio:z.boolean().default(true),publishVideo:z.boolean().default(true),canPublishData:z.boolean().default(true)}),req.body??{});if(!b)return;const access=await roomAccess(rid.data,who(req));if(!access.rowCount)return fail(res,404,'ROOM_NOT_FOUND','The requested room does not exist or you do not have access.');const user=await profile(who(req))??await syncProfile(who(req));const livekit=await issueRoomToken({userId:who(req),name:user.name,roomName:rid.data,...b});return res.json({token:livekit.token,room:{id:rid.data,name:access.rows[0].name},livekit:{url:livekit.url},expiresAt:livekit.expiresAt})}))
api.post('/calls',wrap(async(req,res)=>{const b=input(res,z.object({roomId:uuid,type:z.enum(['VOICE','VIDEO','SCREEN_SHARE'])}),req.body);if(!b)return;const access=await roomAccess(b.roomId,who(req));if(!access.rowCount)return fail(res,404,'ROOM_NOT_FOUND','The requested room does not exist or you do not have access.');const db=database(),cx=await db.connect();try{await cx.query('BEGIN');const active=await cx.query("SELECT id FROM call_history WHERE room_id=$1 AND status='ACTIVE' LIMIT 1",[b.roomId]);let call;if(active.rowCount){call=(await cx.query('SELECT id,room_id AS "roomId",started_by AS "startedBy",type,status,started_at AS "startedAt" FROM call_history WHERE id=$1',[active.rows[0].id])).rows[0]}else{call=(await cx.query('INSERT INTO call_history(room_id,started_by,type) VALUES($1,$2,$3) RETURNING id,room_id AS "roomId",started_by AS "startedBy",type,status,started_at AS "startedAt"',[b.roomId,who(req),b.type])).rows[0]}await cx.query('INSERT INTO call_participants(call_id,user_id) VALUES($1,$2) ON CONFLICT(call_id,user_id) DO UPDATE SET joined_at=now(),left_at=NULL',[call.id,who(req)]);await cx.query('COMMIT');return res.status(active.rowCount?200:201).json({call})}catch(e){await cx.query('ROLLBACK');throw e}finally{cx.release()}}))
api.get('/calls/history',wrap(async(req,res)=>{const page=z.coerce.number().int().min(1).default(1).safeParse(req.query.page),limit=z.coerce.number().int().min(1).max(100).default(20).safeParse(req.query.limit);if(!page.success||!limit.success)return fail(res,422,'VALIDATION_ERROR','Invalid pagination parameters.');const db=database(),u=who(req),count=await db.query('SELECT count(DISTINCT c.id)::int AS total FROM call_history c LEFT JOIN call_participants p ON p.call_id=c.id WHERE c.started_by=$1 OR p.user_id=$1',[u]),rows=await db.query(`SELECT DISTINCT c.id,c.room_id AS "roomId",c.type,c.status,c.started_at AS "startedAt",c.ended_at AS "endedAt" FROM call_history c LEFT JOIN call_participants p ON p.call_id=c.id WHERE c.started_by=$1 OR p.user_id=$1 ORDER BY c.started_at DESC LIMIT $2 OFFSET $3`,[u,limit.data,(page.data-1)*limit.data]);const total=count.rows[0].total;return res.json({calls:rows.rows,pagination:{page:page.data,limit:limit.data,total,hasNextPage:page.data*limit.data<total}})}))
api.get('/calls/:callId',wrap(async(req,res)=>{const cid=uuid.safeParse(param(req,'callId'));if(!cid.success)return fail(res,422,'VALIDATION_ERROR','Invalid call ID.');const r=await database().query(`SELECT c.id,c.room_id AS "roomId",c.type,c.status,c.started_at AS "startedAt",c.ended_at AS "endedAt" FROM call_history c WHERE c.id=$1 AND (c.started_by=$2 OR EXISTS(SELECT 1 FROM call_participants p WHERE p.call_id=c.id AND p.user_id=$2))`,[cid.data,who(req)]);return r.rowCount?res.json({call:r.rows[0]}):fail(res,404,'CALL_NOT_FOUND','Call not found.')}))
api.patch('/calls/:callId',wrap(async(req,res)=>{const cid=uuid.safeParse(param(req,'callId'));if(!cid.success)return fail(res,422,'VALIDATION_ERROR','Invalid call ID.');const b=input(res,z.object({status:z.literal('ENDED'),endedAt:z.iso.datetime().optional()}),req.body);if(!b)return;const db=database(),cx=await db.connect();try{await cx.query('BEGIN');const call=await cx.query(`SELECT c.id FROM call_history c WHERE c.id=$1 AND c.status='ACTIVE' AND (c.started_by=$2 OR EXISTS(SELECT 1 FROM call_participants p WHERE p.call_id=c.id AND p.user_id=$2)) FOR UPDATE`,[cid.data,who(req)]);if(!call.rowCount){await cx.query('ROLLBACK');return fail(res,404,'CALL_NOT_FOUND','Active call not found.')}await cx.query("UPDATE call_history SET status='ENDED',ended_at=COALESCE($2::timestamptz,now()) WHERE id=$1",[cid.data,b.endedAt??null]);await cx.query('UPDATE call_participants SET left_at=now() WHERE call_id=$1 AND user_id=$2 AND left_at IS NULL',[cid.data,who(req)]);const result=await cx.query(`SELECT id,room_id AS "roomId",type,status,started_at AS "startedAt",ended_at AS "endedAt" FROM call_history WHERE id=$1`,[cid.data]);await cx.query('COMMIT');return res.json({call:result.rows[0]})}catch(e){await cx.query('ROLLBACK');throw e}finally{cx.release()}}))
