CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE room_type AS ENUM ('PRIVATE_CALL','GROUP_CALL','STUDY_ROOM');
CREATE TYPE room_role AS ENUM ('OWNER','MODERATOR','MEMBER');
CREATE TYPE friend_request_status AS ENUM ('PENDING','ACCEPTED','REJECTED','CANCELLED');
CREATE TYPE call_type AS ENUM ('VOICE','VIDEO','SCREEN_SHARE');
CREATE TYPE call_status AS ENUM ('ACTIVE','ENDED');
CREATE TABLE users (id text PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 128), name text NOT NULL DEFAULT '', username text UNIQUE, avatar_url text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE friends (user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, friend_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,friend_id), CHECK(user_id <> friend_id));
CREATE TABLE friend_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sender_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, receiver_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, status friend_request_status NOT NULL DEFAULT 'PENDING', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(sender_id <> receiver_id));
CREATE UNIQUE INDEX friend_requests_pending_pair ON friend_requests(LEAST(sender_id,receiver_id),GREATEST(sender_id,receiver_id)) WHERE status='PENDING';
CREATE TABLE study_groups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK(length(name) BETWEEN 1 AND 100), created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE study_rooms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK(length(name) BETWEEN 1 AND 100), type room_type NOT NULL, created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT, study_group_id uuid REFERENCES study_groups(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE room_members (room_id uuid NOT NULL REFERENCES study_rooms(id) ON DELETE CASCADE, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, role room_role NOT NULL DEFAULT 'MEMBER', joined_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(room_id,user_id));
CREATE INDEX room_members_user_idx ON room_members(user_id,joined_at DESC);
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX notifications_user_unread_idx ON notifications(user_id,created_at DESC) WHERE read_at IS NULL;
CREATE TABLE call_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), room_id uuid NOT NULL REFERENCES study_rooms(id) ON DELETE CASCADE, started_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT, type call_type NOT NULL, status call_status NOT NULL DEFAULT 'ACTIVE', started_at timestamptz NOT NULL DEFAULT now(), ended_at timestamptz, CHECK(ended_at IS NULL OR ended_at >= started_at));
CREATE TABLE call_participants (call_id uuid NOT NULL REFERENCES call_history(id) ON DELETE CASCADE, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, joined_at timestamptz NOT NULL DEFAULT now(), left_at timestamptz, PRIMARY KEY(call_id,user_id));
CREATE INDEX call_history_started_by_idx ON call_history(started_by,started_at DESC);
CREATE INDEX call_history_room_idx ON call_history(room_id,started_at DESC);
