type ClerkInstance = InstanceType<typeof import('@clerk/clerk-js').Clerk>
type LiveKitRoom = import('livekit-client').Room

let clerk: ClerkInstance | null = null
let room: LiveKitRoom | null = null
let activeCallId: string | null = null
let authDialog: HTMLDialogElement | null = null
let callDialog: HTMLDialogElement | null = null
const key = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY as string | undefined
const setStatus = (message:string) => {const el=document.querySelector<HTMLElement>('#infra-status');if(el){el.textContent=message;el.hidden=!message}}
const api = async <T>(path:string,init:RequestInit={}):Promise<T>=>{const token=await clerk?.session?.getToken();const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...init.headers}});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error?.message??`Request failed (${response.status})`)}return response.status===204?undefined as T:response.json() as Promise<T>}
const actionButton=(label:string,action:string)=>`<button class="button button-secondary infra-button" data-infra="${action}">${label}</button>`
function ensureShell(){
 if(!document.querySelector('#infra-controls'))document.body.insertAdjacentHTML('beforeend',`<div id="infra-controls" class="infra-controls"><span id="infra-status" class="infra-status" role="status" hidden></span><button id="account-button" class="button button-secondary infra-button">Account</button><button id="call-open" class="button button-primary infra-button">Study call</button></div><dialog id="auth-dialog" class="infra-dialog"><div class="dialog-top"><h2>Studyspace account</h2><button class="icon-button" data-close="auth" aria-label="Close">×</button></div><div id="auth-content"></div></dialog><dialog id="call-dialog" class="infra-dialog call-dialog"><div class="dialog-top"><h2>Study call</h2><button class="icon-button" data-close="call" aria-label="Close">×</button></div><div id="call-content"><label>Room ID<input id="room-id" autocomplete="off" placeholder="Paste a room ID"></label><label>Room name<input id="room-name" maxlength="100" value="Study room"></label><div class="infra-actions">${actionButton('Create room','create-room')}${actionButton('Join room','join-room')}</div><p id="call-state" role="status">Sign in to create or join a study call.</p><div id="participant-list" class="participant-list"></div><div id="media-grid" class="media-grid"></div><div id="call-controls" class="infra-actions" hidden>${actionButton('Mute mic','mic')}${actionButton('Turn camera off','camera')}${actionButton('Share screen','screen')}${actionButton('Leave call','leave')}</div><label id="audio-device-wrap" hidden>Microphone<select id="audio-device"></select></label></div></dialog>`)
 authDialog=document.querySelector<HTMLDialogElement>('#auth-dialog');callDialog=document.querySelector<HTMLDialogElement>('#call-dialog')
}
async function refreshAccount(){
 const target=document.querySelector<HTMLElement>('#auth-content');if(!target||!clerk)return
 if(clerk.isSignedIn){const button=document.querySelector<HTMLButtonElement>('#account-button');if(button)button.textContent=clerk.user?.firstName??'Account';const u=clerk.user;target.innerHTML=`<div class="account-summary"><img src="${u?.imageUrl??''}" alt=""/><div><strong>${u?.fullName??u?.username??'Signed in'}</strong><span>${u?.primaryEmailAddress?.emailAddress??''}</span></div></div><div class="infra-actions"><button class="button button-secondary" data-infra="profile">Manage profile</button><button class="button button-secondary" data-infra="signout">Sign out</button></div><p class="account-hint">Clerk secures your identity and API access. Study data remains browser-local.</p>`;try{await api('/api/me')}catch(e){setStatus(e instanceof Error?e.message:'Profile unavailable.')}}
 else{const button=document.querySelector<HTMLButtonElement>('#account-button');if(button)button.textContent='Sign in';target.innerHTML=`<p class="account-hint">Sign in to securely join study rooms.</p><div class="infra-actions"><button class="button button-primary" id="show-signin">Sign in</button><button class="button button-secondary" id="show-signup">Create account</button></div><div id="clerk-mount" class="clerk-mount"></div>`;const mount=target.querySelector<HTMLDivElement>('#clerk-mount')!;clerk.mountSignIn(mount,{signUpUrl:'#signup',routing:'hash'});target.querySelector('#show-signin')?.addEventListener('click',()=>clerk?.mountSignIn(mount,{signUpUrl:'#signup',routing:'hash'}));target.querySelector('#show-signup')?.addEventListener('click',()=>clerk?.mountSignUp(mount,{signInUrl:'#signin',routing:'hash'}))}
}
function updateCallUi(message?:string){const state=document.querySelector<HTMLElement>('#call-state');if(state&&message)state.textContent=message;if(!room)return;const participants=document.querySelector<HTMLElement>('#participant-list');if(participants)participants.innerHTML=[room.localParticipant,...room.remoteParticipants.values()].map(p=>`<span class="participant-pill">${p.name??p.identity}${room?.activeSpeakers.some(a=>a.identity===p.identity)?' · speaking':''}</span>`).join('');const grid=document.querySelector<HTMLElement>('#media-grid');if(grid)for(const p of [room.localParticipant,...room.remoteParticipants.values()])for(const pub of p.trackPublications.values())if(pub.track&&pub.kind==='video'){const key=`track-${pub.track.sid}`;if(!grid.querySelector(`[data-track="${CSS.escape(key)}"]`)){const video=document.createElement('video');video.dataset.track=key;video.autoplay=true;video.playsInline=true;video.muted=p.identity===room.localParticipant.identity;video.setAttribute('aria-label',p.name??p.identity);pub.track.attach(video);grid.append(video)}}}

async function connectRoom(roomId:string){
 if(!clerk?.isSignedIn){authDialog?.showModal();setStatus('Sign in before joining a room.');return}
 const state=document.querySelector<HTMLElement>('#call-state');if(state)state.textContent='Checking room access…'
 const issued=await api<{token:string;room:{id:string;name:string};livekit:{url:string}}>('/api/rooms/'+encodeURIComponent(roomId)+'/token',{method:'POST',body:JSON.stringify({publishAudio:true,publishVideo:true,canPublishData:true})});const call=await api<{call:{id:string}}>('/api/calls',{method:'POST',body:JSON.stringify({roomId,type:'VIDEO'})})
 const {Room,RoomEvent}=await import('livekit-client')
 room=new Room({adaptiveStream:true,dynacast:true})
 room.on(RoomEvent.ParticipantConnected,()=>updateCallUi());room.on(RoomEvent.ParticipantDisconnected,()=>updateCallUi());room.on(RoomEvent.TrackSubscribed,()=>updateCallUi());room.on(RoomEvent.TrackUnsubscribed,()=>updateCallUi());room.on(RoomEvent.ActiveSpeakersChanged,()=>updateCallUi());room.on(RoomEvent.ConnectionStateChanged,s=>updateCallUi(`Connection: ${s}`));room.on(RoomEvent.Disconnected,()=>updateCallUi('Disconnected. You can rejoin the room.'))
 if(state)state.textContent='Connecting to LiveKit…'
 await room.connect(issued.livekit.url,issued.token);await room.localParticipant.setMicrophoneEnabled(true);await room.localParticipant.setCameraEnabled(true)
 document.querySelector<HTMLElement>('#call-controls')!.hidden=false;document.querySelector<HTMLInputElement>('#room-id')!.value=roomId;if(state)state.textContent=`Connected to ${issued.room.name}`
 activeCallId=call.call.id;await refreshAudioDevices();updateCallUi();window.dispatchEvent(new CustomEvent('studyspace:call-started',{detail:{callId:call.call.id,roomId}}))
}
async function refreshAudioDevices(){if(!room)return;const {Room}=await import('livekit-client');const wrap=document.querySelector<HTMLElement>('#audio-device-wrap')!,select=document.querySelector<HTMLSelectElement>('#audio-device')!;try{const devices=await Room.getLocalDevices('audioinput');select.innerHTML=devices.map(d=>`<option value="${d.deviceId}">${d.label||'Microphone'}</option>`).join('');wrap.hidden=devices.length<2;if(devices.length)select.value=room.getActiveDevice('audioinput')??devices[0].deviceId}catch{wrap.hidden=true}}
async function leaveRoom(){if(!room)return;const callId=activeCallId;await room.disconnect();room=null;activeCallId=null;document.querySelector<HTMLElement>('#call-controls')!.hidden=true;document.querySelector<HTMLElement>('#media-grid')!.replaceChildren();document.querySelector<HTMLElement>('#participant-list')!.replaceChildren();updateCallUi('You left the call.');if(callId)await api(`/api/calls/${callId}`,{method:'PATCH',body:JSON.stringify({status:'ENDED'})}).catch(showError)}
function showError(error:unknown){setStatus(error instanceof Error?error.message:'The request failed. Please try again.')}
export async function initializeInfrastructure(){
 ensureShell()
 if(!key||key.includes('replace_me')){setStatus('Set VITE_CLERK_PUBLISHABLE_KEY and server credentials in .env to enable accounts/calls.');document.querySelector('#auth-content')!.innerHTML='<p class="account-hint">Authentication is not configured. Copy .env.example to .env and add your Clerk publishable key plus matching server credentials.</p>';return}
 try{const {Clerk}=await import('@clerk/clerk-js');clerk=new Clerk(key);await clerk.load();await refreshAccount();clerk.addListener(()=>{void refreshAccount()})}catch(e){showError(e)}
 document.body.addEventListener('click',event=>{const target=event.target as HTMLElement;const close=target.closest<HTMLElement>('[data-close]');if(close){(close.dataset.close==='auth'?authDialog:callDialog)?.close();return}if(target.closest('#account-button')){void refreshAccount();authDialog?.showModal();return}if(target.closest('#call-open')){callDialog?.showModal();return}const action=target.closest<HTMLElement>('[data-infra]')?.dataset.infra;if(!action)return;void (async()=>{try{if(action==='signout'){await clerk?.signOut();authDialog?.close();return}if(action==='profile'){clerk?.openUserProfile();return}if(action==='create-room'){const name=document.querySelector<HTMLInputElement>('#room-name')?.value.trim()||'Study room';const r=await api<{room:{id:string}}>('/api/rooms',{method:'POST',body:JSON.stringify({name,type:'STUDY_ROOM'})});document.querySelector<HTMLInputElement>('#room-id')!.value=r.room.id;await connectRoom(r.room.id);return}if(action==='join-room'){const id=document.querySelector<HTMLInputElement>('#room-id')?.value.trim()??'';if(!id)throw new Error('Enter a room ID.');await connectRoom(id);return}if(!room)return;if(action==='mic'){const enabled=!room.localParticipant.isMicrophoneEnabled;await room.localParticipant.setMicrophoneEnabled(enabled);const b=document.querySelector('[data-infra="mic"]');if(b)b.textContent=enabled?'Mute mic':'Unmute mic'}else if(action==='camera'){const enabled=!room.localParticipant.isCameraEnabled;await room.localParticipant.setCameraEnabled(enabled);const b=document.querySelector('[data-infra="camera"]');if(b)b.textContent=enabled?'Turn camera off':'Turn camera on'}else if(action==='screen'){const enabled=!room.localParticipant.isScreenShareEnabled;await room.localParticipant.setScreenShareEnabled(enabled);const b=document.querySelector('[data-infra="screen"]');if(b)b.textContent=enabled?'Stop sharing':'Share screen'}else if(action==='leave')await leaveRoom()}catch(e){showError(e);const state=document.querySelector<HTMLElement>('#call-state');if(state)state.textContent=e instanceof Error?e.message:'Call operation failed.'}})()})
 document.querySelector<HTMLSelectElement>('#audio-device')?.addEventListener('change',event=>{const device=(event.target as HTMLSelectElement).value;void room?.switchActiveDevice('audioinput',device).catch(showError)})
 const auth=authDialog,callUi=callDialog;auth?.addEventListener('click',event=>{if(event.target===auth)auth.close()});callUi?.addEventListener('click',event=>{if(event.target===callUi)callUi.close()})
}
