import { duration, escapeHtml, type AppData, type Subject } from './store'
import { empty, icon, panelHead } from './ui'

const pathCard = (path: Subject, data: AppData) => {
 const percent = Math.min(100, Math.round(path.minutes / path.goal * 100))
 const sessions = data.sessions.filter(session => session.subjectId === path.id)
 return `<article class="course-card"><div class="course-top"><span class="subject-mark large-mark" style="--subject-color:${escapeHtml(path.color)}">${escapeHtml((path.code || path.name).slice(0, 2).toUpperCase())}</span><button class="icon-button" data-action="edit-subject" data-id="${escapeHtml(path.id)}" aria-label="Edit ${escapeHtml(path.name)}">${icon('arrow')}</button></div><p class="course-code">${escapeHtml(path.code || 'YOUR LEARNING SPACE')}</p><h2>${escapeHtml(path.name)}</h2><p class="course-note">${data.questions.filter(question => question.subjectId === path.id).length} practice prompts · ${sessions.length} focus sessions</p><div class="course-progress"><div class="course-progress-caption"><span>Your time goal</span><strong>${percent}%</strong></div><div class="progress-track"><span style="width:${percent}%;--subject-color:${escapeHtml(path.color)}"></span></div><span class="course-minutes">${duration(path.minutes)} explored · ${duration(path.goal)} personal goal</span></div><div class="course-actions"><button class="button button-soft" data-action="log-time" data-id="${escapeHtml(path.id)}">${icon('clock', 15)} Log learning time</button><button class="button button-quiet" data-action="delete-subject" data-id="${escapeHtml(path.id)}" aria-label="Delete ${escapeHtml(path.name)}">${icon('trash', 15)}</button></div></article>`
}

const pathName = (data: AppData, id: string) => data.subjects.find(path => path.id === id)?.name ?? 'Personal learning'

export function learningPathsView(data: AppData) {
 const sessions = [...data.sessions].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 8)
 return `<section class="page-heading"><div><p class="eyebrow">SHAPED AROUND WHAT YOU WANT TO LEARN</p><h1>Learning paths<span class="title-period">.</span></h1><p class="heading-copy">A skill, a subject, a curious detour. Name each space in your own way.</p></div><button class="button button-primary" data-action="add-subject">${icon('plus')} Create a path</button></section>${data.subjects.length ? `<section class="subject-cards">${data.subjects.map(path => pathCard(path, data)).join('')}</section>` : `<section class="panel">${empty('Start anywhere','Create a space for anything you want to explore—no course or curriculum required.','add-subject','Create your first path')}</section>`}<section class="panel session-panel">${panelHead('TIME WELL SPENT','Recent learning sessions')}${sessions.length ? `<div class="session-list">${sessions.map(session => `<div class="session-row"><span class="session-dot" style="--subject-color:${escapeHtml(data.subjects.find(path => path.id === session.subjectId)?.color ?? '#718071')}"></span><strong>${escapeHtml(pathName(data, session.subjectId))}</strong><span>${escapeHtml(session.note || 'Learning session')}</span><time>${escapeHtml(new Date(`${session.date}T12:00:00`).toLocaleDateString('en', { month: 'short', day: 'numeric' }))}</time><b>${duration(session.minutes)}</b></div>`).join('')}</div>` : '<p class="subtle-copy session-placeholder">Focus sessions will appear here when you start exploring.</p>'}</section>`
}
