import { escapeHtml, type AppData, type Task } from './store'
import { empty, icon } from './ui'

const pathFor = (data: AppData, id: string) => data.subjects.find(path => path.id === id)
const dueLabel = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('en', { month: 'short', day: 'numeric' }) : 'Whenever you’re ready'

export function planView(data: AppData) {
 const open = data.tasks.filter(task => !task.done).sort((a, b) => (a.due || '9999').localeCompare(b.due || '9999'))
 const done = data.tasks.filter(task => task.done)
 const row = (task: Task) => `<article class="plan-row${task.done ? ' task-complete' : ''}"><button class="task-check${task.done ? ' checked' : ''}" data-action="toggle-task" data-id="${escapeHtml(task.id)}" aria-label="${task.done ? 'Reopen' : 'Complete'} ${escapeHtml(task.title)}">${task.done ? icon('check',14) : ''}</button><div class="task-row-copy"><strong>${escapeHtml(task.title)}</strong><span>${escapeHtml(pathFor(data,task.subjectId)?.name ?? 'Personal task')} · ${escapeHtml(task.due ? dueLabel(task.due) : 'Whenever you’re ready')}</span></div><button class="icon-button" data-action="delete-task" data-id="${escapeHtml(task.id)}" aria-label="Delete task">${icon('trash',15)}</button></article>`
 return `<section class="page-heading"><div><p class="eyebrow">INTENTION, NOT PRESSURE</p><h1>My plan<span class="title-period">.</span></h1><p class="heading-copy">A flexible list of next steps. Add a due date if it helps; skip it if it doesn’t.</p></div><button class="button button-primary" data-action="add-task">${icon('plus')} Add a task</button></section><section class="panel plan-panel"><div class="plan-section-heading"><div><p class="eyebrow">YOUR NEXT STEPS</p><h2>In your own time <span>${open.length}</span></h2></div></div>${open.length ? `<div class="plan-list">${open.map(row).join('')}</div>` : empty('Room to begin again','Add one small thing you would like to learn, make, or understand.','add-task','Add a task','check')}</section>${done.length ? `<section class="panel plan-panel completed-panel"><div class="plan-section-heading"><div><p class="eyebrow">YOU SHOWED UP</p><h2>Completed <span>${done.length}</span></h2></div></div><div class="plan-list">${done.slice().reverse().map(row).join('')}</div></section>` : ''}`
}

export function notesView(data: AppData, search: string) {
 const filtered = data.notes.filter(note => `${note.title} ${note.content} ${pathFor(data,note.subjectId)?.name ?? ''}`.toLowerCase().includes(search.toLowerCase()))
 const cards = filtered.map(note => `<article class="note-card"><div class="note-card-heading"><span class="note-path">${escapeHtml(pathFor(data,note.subjectId)?.name ?? 'Personal note')}</span><button class="icon-button" data-action="delete-note" data-id="${escapeHtml(note.id)}" aria-label="Delete ${escapeHtml(note.title)}">${icon('trash',15)}</button></div><button class="note-open" data-action="edit-note" data-id="${escapeHtml(note.id)}"><strong>${escapeHtml(note.title)}</strong><span>${escapeHtml(note.content || 'An empty page, ready when you are.')}</span><small>Edited ${escapeHtml(dueLabel(note.updated))}</small></button></article>`).join('')
 return `<section class="page-heading"><div><p class="eyebrow">THOUGHTS, ALL IN ONE PLACE</p><h1>Notes<span class="title-period">.</span></h1><p class="heading-copy">Keep the useful bits. Jot something down before it slips away.</p></div><button class="button button-primary" data-action="add-note">${icon('plus')} New note</button></section><section class="notes-toolbar"><label class="search-box">${icon('search')}<input id="note-search" type="search" placeholder="Find a note…" value="${escapeHtml(search)}" aria-label="Search notes"></label><span>${filtered.length} ${filtered.length === 1 ? 'note' : 'notes'} · saved on this device</span></section>${cards ? `<section class="notes-grid">${cards}</section>` : search ? `<section class="panel">${empty('No notes found','Try another search, or start a fresh page.','add-note','Write a note','book')}</section>` : `<section class="panel">${empty('A place for the things you learn','Capture a question, a useful explanation, or the idea you want to return to.','add-note','Write your first note','book')}</section>`}`
}
