import { duration, escapeHtml, today, type AppData, type Question, type Subject, type View } from './store'
export const icon = (name: string, size = 18) => {
 const paths: Record<string, string> = { grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/>',book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/>',cards:'<rect x="3" y="5" width="14" height="16" rx="2"/><path d="M7 3h12a2 2 0 0 1 2 2v14m-14-9h6m-6 4h6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',plus:'<path d="M12 5v14m-7-7h14"/>',search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>',arrow:'<path d="M7 17 17 7M7 7h10v10"/>',check:'<path d="m5 12 4 4L19 6"/>',spark:'<path d="m12 3 2 6 6 2-6 2-2 6-2-6-6-2 6-2 2-6z"/>',trash:'<path d="M3 6h18m-2 0-1 14H6L5 6m4 0V4h6v2m-5 4v6m4-6v6"/>',close:'<path d="m18 6-12 12M6 6l12 12"/>',chevron:'<path d="m9 18 6-6-6-6"/>',download:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4m4-5 5 5 5-5m-5 5V3"/>' }
 return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] ?? paths.spark}</svg>`
}
export function header(data: AppData) {
 const item = (view: View, text: string, symbol: string, count = '') => `<button class="nav-item${data.view === view ? ' nav-active' : ''}" data-view="${view}">${icon(symbol)}<span>${text}</span>${count ? `<span class="nav-count">${count}</span>` : ''}</button>`
 return `<div class="app-shell"><aside class="sidebar"><button class="wordmark brand-button" data-view="overview" aria-label="Go to overview"><span class="brand-mark">s<span>.</span></span><span class="brand-name">studyspace<span class="brand-edition">YOUR LEARNING SPACE</span></span></button><div class="nav-caption">WORKSPACE</div><nav class="sidebar-nav" aria-label="Main navigation">${item('overview','Home','grid')}${item('subjects','Learning paths','book',String(data.subjects.length))}${item('plan','My plan','clock',String(data.tasks.filter(task=>!task.done).length))}${item('notes','Notes','book',String(data.notes.length))}${item('questions','Practice','cards',String(data.questions.length))}${item('review','Review','spark',String(data.questions.filter(q=>q.due<=today()).length))}</nav><div class="sidebar-spacer"></div><div class="local-note"><span class="local-icon">${icon('check',16)}</span><div><strong>Saved on this device</strong><span>Your data stays yours.</span></div></div><div class="sidebar-bottom">YOUR SPACE · STUDY SMARTER</div></aside><main class="main-area"><header class="topbar"><button class="mobile-brand" data-view="overview">studyspace<span>.</span></button><span class="topbar-label">YOUR PERSONAL STUDY DESK</span><span class="offline-chip"><span></span> ALL SAVED</span></header>`
}
export function footer() { return '<footer class="page-footer"><span>Learn in a way that works for you.</span><span>Everything stays on this device.</span></footer></main></div><div id="toast" class="toast" aria-live="polite"></div>' }
export function heading(eyebrow: string, title: string, copy: string, button: string, action: string) { return `<section class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="heading-copy">${copy}</p></div><button class="button button-primary" data-action="${action}">${icon('plus')} ${button}</button></section>` }
export function panelHead(eyebrow: string, title: string, link = '', view: View = 'overview') { return `<div class="panel-heading"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${link ? `<button class="text-link" data-view="${view}">${link} ${icon('chevron',15)}</button>` : ''}</div>` }
export function empty(title: string, copy: string, action: string, button: string, symbol = 'book') { return `<div class="empty-state"><div class="empty-art">${icon(symbol,23)}</div><h3>${title}</h3><p>${copy}</p><button class="button button-primary" data-action="${action}">${icon('plus')} ${button}</button></div>` }
export function subjectRow(item: Subject) { const pct=Math.min(100,Math.round(item.minutes/item.goal*100));return `<article class="subject-row"><span class="subject-mark" style="--subject-color:${escapeHtml(item.color)}">${escapeHtml((item.code||item.name).slice(0,2).toUpperCase())}</span><div class="subject-main"><div class="subject-name-line"><strong>${escapeHtml(item.name)}</strong><span>${duration(item.minutes)} <span class="muted-inline">/ ${duration(item.goal)}</span></span></div><div class="progress-track"><span style="width:${pct}%;--subject-color:${escapeHtml(item.color)}"></span></div></div><span class="progress-percent">${pct}%</span></article>` }
export function questionPreview(q: Question, subjectName: string, color: string) { return `<article class="question-preview"><span class="subject-mark small-mark" style="--subject-color:${escapeHtml(color)}">${icon('cards',16)}</span><div><strong>${escapeHtml(q.text)}</strong><span>${escapeHtml(subjectName)} · ${escapeHtml(q.topic||'General')}</span></div><button class="icon-button" data-action="practice" data-id="${escapeHtml(q.id)}" aria-label="Practice question">${icon('arrow')}</button></article>` }
